### PR TITLE
💄 Styling fixes & prop bug fix

### PR DESCRIPTION
**Pull request by eliascodes**
This is mainly to get away from the silly 90% thing we were
doing everywhere. Using 100% width and setting explicit margin
and padding is better, instead of having layouts implicitly depend
on elements not using the full width of their container.

* Make LabelledInput and LabelledSelect 100% width
* Reduce padding on LabelledSelect to improve alignment w LabelledInput
* Update several pages w/ Button width 90% -> 100%
* Add margin/padding to places that were relying on this 90% width thing

In addition, fix a bug with the newly introduced `NavHeader` component; `Fragment` elements are not allowed to have click handlers.

### CODE REVIEW

**Comment by astroash** [comment]
@eliascodes I feel like now we're missing padding on a number of the pages

eg.
screenshot 2019-01-29 at 21 40 12

**Comment by eliascodes** [comment]
Where is there missing padding on that page?

**Comment by astroash** [comment]
@eliascodes re conversation, see alignment changes on settings page:

Before:
screenshot 2019-01-30 at 10 32 53

After:
screenshot 2019-01-30 at 10 32 50

The changes in input/button width has changed layout throughout the app. IMO 90% width should be replaced with margin.

**Comment by astroash** [comment]
Input boxes are looking a bit janky on the settings page. I think they should either be centred or the same width as the box above.

screenshot 2019-01-30 at 14 18 46

**Comment by eliascodes** [comment]
Hmm, missed this because I was only looking at it on iPad resolution.

**Comment by astroash** [comment]
Can we add a little padding to the signup form 🙏🏽. It looks so much nicer!

Without padding:
screenshot 2019-01-30 at 16 39 51

With padding:
screenshot 2019-01-30 at 16 39 58

Also, happy for this to be solved in another PR, but as there's no set height on the `img` element there's a very obvious page rejig on response. This was there before, but the `img` was smaller so it was less obvious:
settings page

**Comment by eliascodes** [comment]
> Can we add a little padding to the signup form 🙏🏽. It looks so much nicer!

I can barely tell the difference. Is this blocking?

**Comment by astroash** [comment]
No...

**Pull request merged**
