### PR TITLE
⬆️ Update dependencies

### PR DESCRIPTION
**Pull request by eliascodes**
Except for those likely to have breaking changes

* Major bumps: jest-dom
* Minor bumps: eslint-plugins, moment, polished, prop-types, react, ramda, qs, react-scripts, react-spinners, styled-components, react-testing-library, axios-mock-adapter

**Changes:**
eslint-plugin-react 
- no breaking changes, see changelog https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md

moment 
- no breaking changes, see changelog https://github.com/moment/moment/blob/develop/CHANGELOG.md

polished
- no breaking changes, see semantic versioning https://github.com/styled-components/polished/releases?after=v2.3.1

qs
- no breaking changes, see changelog https://github.com/ljharb/qs/blob/master/CHANGELOG.md

ramda
- a number of deprecated methods, all unused in codebase
- see changes here https://github.com/ramda/ramda/issues/2702
- note evolve now works with arrays ✨

react
- no breaking changes, see changelog here https://github.com/facebook/react/blob/master/CHANGELOG.md
- note hooks now stable ✨

react-scripts
- no breaking changes, see changelog https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md

styled-componenets
- no breaking changes, see changelog https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md

axios-mock-adapter
- no breaking changes, see semantic versioning https://github.com/ctimmerm/axios-mock-adapter/releases

jest-dom
- breaking changes:
  - toHaveTextContent to be case-sensitive
- see semantic versioning https://github.com/gnapse/jest-dom/releases

react-testing-library
- no breaking changes, see semantic versioning https://github.com/kentcdodds/react-testing-library/releases

### CODE REVIEW

**Comment by astroash** [comment]
@eliascodes do you want this manually testing?

**Comment by eliascodes** [comment]
I flew through most of the pages quickly. Up to you how thorough you want to be, I'm happy.

**Comment by astroash** [comment]
@eliascodes can this branch be rebased onto staging? It's _old..._

**Comment by eliascodes** [comment]
What would that do? The diff is already minimal, and it'll be re-based when it's squashed.

**Comment by astroash** [comment]
I would like to be able to manually test this PR.

**Comment by eliascodes** [comment]
Why do you think it's old? It's at the tip of staging.

screenshot 2019-02-18 at 10 57 27

**Comment by astroash** [comment]
@eliascodes my apologies, I was looking at `update-deps` on twine-api

**Comment by astroash** [comment]
**Manual testing:**

- [ ] breaks styling for react spinners. From changelog:
> 0.5.0
>  - Update emotion package to emotion 10
>  - Breaking change: replaced className prop with css prop to match Emotion 10.

**Comment by eliascodes** [comment]
> breaks styling for react spinners

Looks like this is because `styled-components` passes down its styling using the `className` prop, which is now no longer passed down by react-spinners. I'm downgrading back to `0.4.8`. In future we may wish to consider switching to a spinner library that supports `styled-components` (e.g. some of the ones on this page: https://www.styled-components.com/ecosystem)

**Pull request merged**
