### PR TITLE
🐛 display message when no activities scheduled

### LINKED ISSUE #671: Display message & nav when no activities scheduled
screenshot 2019-02-05 at 15 34 13

### PR DESCRIPTION
**Pull request by eliascodes**
Fixes #671

Related to #665

* Add a message and a back button when there are no activities

### CODE REVIEW

**Comment by astroash** [comment]
Hmmm, does it make sense to get visitors to scan their QR code if there are no activites this day? I feel like the "sorry no go" screen should be after clicking the "sign in" button.

**Comment by astroash** [comment]
@eliascodes titles a bit janky, also doesn't really make sense to have the privacy disclaimer on this page anymore, maybes it just needs to be a separate page?

Happy for this to do in as it was before if you would prefer. 

screenshot 2019-02-07 at 14 58 48

**Comment by eliascodes** [comment]
Desktop:
screenshot 2019-02-07 at 16 47 35

iPad Pro (hi res):
screenshot 2019-02-07 at 16 48 08

iPad (lo-res):
screenshot 2019-02-07 at 16 48 18

**Comment by astroash** [comment]
@eliascodes can we get some margin-top on that button? 

Or:
- change title to "No activities scheduled today"
- trash the `p`

**Pull request merged**
