### PR TITLE
🚀 DEPLOYMENT 19-02-19

### PR DESCRIPTION
**Pull request by astroash**
Changes
- 📝 add docs - initial pass of user testing instructions (#681)
- ⬆️ Update dependencies to minor releases (#693)

Partnered PR: https://github.com/TwinePlatform/twine-api/pull/346

Manual testing:

- [x] `CB_ADMIN` can successfully delete an activity
- [x] `CB_ADMIN` can update a `VISITOR`s name to different casing eg ASH -> ash
- [x] as this PR includes dependency changes common user flows should also be tested for unanticipated bugs

### CODE REVIEW

**Comment by mandsmandsmands** [comment]
I've just tested (IE and Chrome)
**CB_ADMIN can successfully delete an activity**
on https://twine-visitor-staging.herokuapp.com and I am still getting  - 500 internal server error

**Comment by astroash** [comment]
@mandsmandsmands 

>on [twine-visitor-staging.herokuapp.com](https://twine-visitor-staging.herokuapp.com) and I am still getting - 500 internal server error

Thanks for highlighting this, this should not be the case.

> * `CB_ADMIN` can update a `VISITOR`s name to different casing

Name fields should be able to change casing or input a new name. Previously we had a 🐛 where case changes would not work

>     * VISITOR - I do not have QR code for this env so need some help with this.

You can either:
- create a new QR code by visitor sign up. For demoing I often create fake email accounts and take a picture of the QR code on my phone
- Go to the Visitors page on the admin dashboard and select (click on) a visitor. This is take you to their details page where you can take a photo of the QR code

**Comment by eliascodes** [comment]
@mandsmandsmands thanks for that!

On your FAIL, it was indeed designed to allow the name to be totally changed, so that's fine (as far as we're concerned). The only thing that was added in this PR was a bug fix allowing casing-only changes to be recognised.

For example, before this, the change `Seldwyn Morgan` -> `seldwyn morgan` wouldn't work (it would just give you the original back again). But `Seldwyn Morgan` to `seldwyn m` would work fine.

> VISITOR - I do not have QR code for this env so need some help with this.

The way we typically do this is one of two ways:
1. Sign up as a new visitor, and then take a picture of the QR code when it's shown on screen
2.  Go to the admin section, to the list of visitors, chose one and take a picture of their QR code when it's shown on their profile view.

**Comment by eliascodes** [comment]
> Thanks for highlighting this, this should not be the case.

This seems to be because the new version was not deployed. I think auto-deploy doesn't go through if any of the checks fail (including coverage). So because coverage dropped (even by <1%) it didn't deploy.

I've manually deployed to staging now though, should be fixed and working.

**Pull request merged**
