### PR TITLE
🚀 DEPLOYMENT 26-01-19

### PR DESCRIPTION
**Pull request by astroash**
**Changes**
- routing changes to allow for client side authorisation of admin dashboard

**Manual Testing:**
- [x] this is a full app restructure all **routing** needs testing. Eg all buttons that take you to another page.
- [x] refreshing on welcome screen should remain on page
- [x] refreshing on admin visitors page should require you to reenter your password and redirects back to admin visitors page

**Partnered PR:** https://github.com/TwinePlatform/twine-api/pull/351

### CODE REVIEW

**Comment by mandsmandsmands** [comment]
1.  Refreshing on welcome screen should remain on page - PASS

**Comment by mandsmandsmands** [comment]
2. refreshing on admin visitors page should require you to reenter your password and redirects back to admin visitors page
Retested with refreshing off the pages: 
Admin > Activities > Refresh > Admin Login > Activities page
Admin > Visitors > Refresh > Admin Login > Visitors page
Admin > Visits > Refresh > Admin Login > Visits page
Admin > Account Settings  > Refresh > Admin Login > Account Settings page
Admin > Feedback > Refresh > Admin Login > Feedback page

All PASS

**Comment by mandsmandsmands** [comment]
3. this is a full app restructure all **routing** needs testing. Eg all buttons that take you to another page
PASS

**Comment by astroash** [comment]
@eliascodes please merge on review/merge of TwinePlatform/twine-api#351

**Pull request merged**
