### PR TITLE
🚀 DEPLOYMENT 05-02-19

### PR DESCRIPTION
**Pull request by astroash**
Standard User Flows:

- [x] sign up new visitor
- [x] login visitor to log visit
- [x] download logs

Additional user testing flows:

- [x] ALL PAGES (😥 styling changes)

_no partnered api pr_

### CODE REVIEW

**Comment by astroash** [comment]
Oh, there’s also the no activities page that needs styling.

**Comment by eliascodes** [comment]
@astroash that's only been added in #653, so let's add that as a comment there.

**Comment by eliascodes** [comment]
Depends what you mean. #653 specifically checks for no-activities on that day and displays a (poorly layed-out) message in that case. If that's what you mean, it should be done in #653. 

In the current app (master/HEAD), if there's no activities, this is displayed:
screenshot 2019-02-05 at 15 34 13

This is pretty bad, but nothing to do with the changes in this PR.

**Comment by astroash** [comment]
I mean, it would be nice if that feature is pulled out and merged to master 😏

**Comment by eliascodes** [comment]
True, but IMO no reason to hold up this deployment.

**Comment by astroash** [comment]
@eliascodes but we're not waiting on this PR for any bug fixes, it's just some refactoring to make our lives easier in the future. 

Adding the no activities page here would actively improve the current ux of the app.

**Comment by astroash** [comment]
Manual testing feedback:
- on Visitors page in admin section, age filter is not cleared after deselecting

**Pull request merged**
